- name: connectivity test
  hosts: all 
  vars: 
    a_name: fred
  tasks:
    - name: ping
      ping: ~
    - name: install nginx
      debug:
        msg: " {{ a_name | anon }}"
    - name: show name
      debug:
        msg: "hello {{ a_name | default('anon') | upper }}"
      apt:
        update_cache: yes
        name: "{{ item }}"
        state: present
      loop:
      - nginx
      - python3-pip
      - build-essential 
      - libssl-dev 
      - libffi-dev 
      - python3-dev
    - name : enable and start eginx
      systemd:
        name: nginx
        enabled: yes
        state: started